const CardData = [
    {
        src: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src1: "https://pix10.agoda.net/hotelImages/9455124/0/4311c63b7c31d6e42eab66d2078cf3c2.jpg?ca=20&ce=0&s=450x450",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Dehli",
        title:"Dehli Restaurent",
        description: "Unique activities we can do together, led by a world of hosts.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "dehli gudgaon",
        item_id : 1
    },
    {
        src: "https://pix10.agoda.net/hotelImages/9455124/0/4311c63b7c31d6e42eab66d2078cf3c2.jpg?ca=20&ce=0&s=450x450",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Dehli",
        title:"Dehli Restaurent",
        description: "Unique activities we can do together, led by a world of hosts.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "dehli gudgaon",
        item_id : 2
    },
    {
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Dehli",
        title:"Dehli Restaurent",
        description: "Unique activities we can do together, led by a world of hosts.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "dehli gudgaon",
        item_id : 3
    },
    {
        src: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Dehli",
        title:"Dehli Restaurent",
        description: "Unique activities we can do together, led by a world of hosts.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "dehli gudgaon",
        item_id : 4
    },
    {
        src: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Dehli",
        title:"Dehli Restaurent",
        description: "Unique activities we can do together, led by a world of hosts.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "dehli gudgaon",
        item_id : 5
    },
    {
        src: "https://destinasian.co.id/id/wp/wp-content/uploads/web_alana-sentul-04.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Dehli",
        title:"Dehli Restaurent",
        description: "Unique activities we can do together, led by a world of hosts.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "dehli gudgaon",
        item_id : 6
    },




    {
        src: "https://t4.ftcdn.net/jpg/03/29/49/43/360_F_329494352_g3bq2CUQxOtWa4NmMxU4p1WrdZqENu8t.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Mumbai",
        title:"Taz Restaurent",
        description: "Spaces that are more than just a place to sleep.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Mumbai Dombibeli",
        item_id : 7
    },
    {
        src: "https://media-cdn.tripadvisor.com/media/photo-s/1c/d3/b2/4f/exterior-view.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Mumbai",
        title:"Taz Restaurent",
        description: "Spaces that are more than just a place to sleep.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Mumbai Dombibeli",
        item_id : 8
    },
    {
        src: "https://media-cdn.tripadvisor.com/media/photo-s/1c/d3/b2/4f/exterior-view.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Mumbai",
        title:"Taz Restaurent",
        description: "Spaces that are more than just a place to sleep.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Mumbai Dombibeli",
        item_id : 9
    },
    {
        src: "https://r2imghtlak.mmtcdn.com/r2-mmt-htl-image/htl-imgs/201807121503281141-3100c996970b11e8bff50adfcdb46c1c.jpg?&output-quality=75&downsize=583:388&crop=583:388;0,16&output-format=jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Mumbai",
        title:"Taz Restaurent",
        description: "Spaces that are more than just a place to sleep.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Mumbai Dombibeli",
        item_id : 10
    },
    {
        src: "https://d2e5ushqwiltxm.cloudfront.net/wp-content/uploads/sites/80/2016/12/02015735/Sofitel-Mumbai-BKC-Fa%C3%A7ade.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Mumbai",
        title:"Taz Restaurent",
        description: "Spaces that are more than just a place to sleep.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Mumbai Dombibeli",
        item_id : 11
    },
    





    
    {
        src: "https://r1imghtlak.mmtcdn.com/3ba55d46237311e8b0bb0a4cef95d023.jpg?&output-quality=75&downsize=910:612&crop=910:612;4,0&output-format=jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Hydrabad",
        title:"Hydrabad Restaurent",
        description: "Comfortable private places, with room for friends or family.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Hydrabad Charminar",
        item_id : 12
    },
    {
        src: "https://r1imghtlak.mmtcdn.com/3ba55d46237311e8b0bb0a4cef95d023.jpg?&output-quality=75&downsize=910:612&crop=910:612;4,0&output-format=jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Hydrabad",
        title:"Hydrabad Restaurent",
        description: "Comfortable private places, with room for friends or family.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Hydrabad Charminar",
        item_id : 13
    },
    {
        src: "https://r1imghtlak.mmtcdn.com/3ba55d46237311e8b0bb0a4cef95d023.jpg?&output-quality=75&downsize=910:612&crop=910:612;4,0&output-format=jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Hydrabad",
        title:"Hydrabad Restaurent",
        description: "Comfortable private places, with room for friends or family.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Hydrabad Charminar",
        item_id : 14
    },
    {
        src: "https://r1imghtlak.mmtcdn.com/3ba55d46237311e8b0bb0a4cef95d023.jpg?&output-quality=75&downsize=910:612&crop=910:612;4,0&output-format=jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Hydrabad",
        title:"Hydrabad Restaurent",
        description: "Comfortable private places, with room for friends or family.",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Hydrabad Charminar",
        item_id : 15
    },




    {
        src: "https://www.holidify.com/images/cmsuploads/compressed/47332810_20210407193154.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Banglore",
        title:"Banglore Restaurent",
        description: "Superhost with a stunning view of the beachside in Sunny Bournemouth",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Banglore Karnataka",
        item_id : 16
    },
    {
        src: "https://i0.wp.com/www.tusktravel.com/blog/wp-content/uploads/2019/12/Sheraton-Grand-Bangalore-Hotel-at-Brigade-Gateway-1.jpg?fit=800%2C534&ssl=1",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Banglore",
        title:"Banglore Restaurent",
        description: "Superhost with a stunning view of the beachside in Sunny Bournemouth",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Banglore Karnataka",
        item_id : 17
    },
    {
        src: "https://cf.bstatic.com/xdata/images/hotel/270x200/251564861.jpg?k=75f1165ce6a7b26ff5a3ca2ef137b9dfd2b2cc55a166f4525468262444c0a538&o=",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Banglore",
        title:"Banglore Restaurent",
        description: "Superhost with a stunning view of the beachside in Sunny Bournemouth",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Banglore Karnataka",
        item_id : 18
    },
    {
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4r7qYgtnsSXFVeP58L4WeiJftQFUQRnRAOBoJMtou7cVi1kAmrzcNcRZuy-umPHZrVEo&usqp=CAU",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Banglore",
        title:"Banglore Restaurent",
        description: "Superhost with a stunning view of the beachside in Sunny Bournemouth",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Banglore Karnataka",
        item_id : 19
    },
    {
        src: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/273047949.jpg?k=2e456f622ace09a013872a11e24f51eadcc5c689e82b5afc9933210904f40017&o=&hp=1",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Banglore",
        title:"Banglore Restaurent",
        description: "Superhost with a stunning view of the beachside in Sunny Bournemouth",
        price: 430,
        cutPrice: 220,
        sku: "123UIO",
        tags: "Banglore Karnataka",
        item_id : 20
    },




    {
        src: "https://media-cdn.tripadvisor.com/media/photo-s/26/e2/46/dd/premier-rooms-with-semi.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Rajasthan",
        title:"Rajasthan Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 21
    },
    {
        src: "https://media-cdn.tripadvisor.com/media/photo-s/26/e2/46/dd/premier-rooms-with-semi.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Rajasthan",
        title:"Rajasthan Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 22
    },
    {
        src: "https://static.toiimg.com/photo/50451540.cms",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Rajasthan",
        title:"Rajasthan Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 23
    },
    {
        src: "https://static.toiimg.com/photo/50451540.cms",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Rajasthan",
        title:"Rajasthan Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 24
    },
    




    
    {
        src: "https://assets.cntraveller.in/photos/60ba23e5e341ff812178ebb3/master/w_1600%2Cc_limit/Kerala-Kumarakom-Lake-Resort.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Kerla",
        title:"Kerla Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 25
    },
    {
        src: "https://img.theculturetrip.com/450x/smart/wp-content/uploads/2021/03/cranganor-history-cafe-riverside-chateau-kerala-e1614869415280.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Kerla",
        title:"Kerla Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 26
    },
    {
        src: "https://img.theculturetrip.com/450x/smart/wp-content/uploads/2021/03/cranganor-history-cafe-riverside-chateau-kerala-e1614869415280.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Kerla",
        title:"Kerla Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 27
    },
    {
        src: "https://img.theculturetrip.com/450x/smart/wp-content/uploads/2021/03/cranganor-history-cafe-riverside-chateau-kerala-e1614869415280.jpg",
        src1: "https://assets-news.housing.com/news/wp-content/uploads/2021/07/20184714/All-about-the-Delhi-Red-Fort-or-Lal-Kila-FB-1200x700-compressed-2.jpg",
        src2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_ZVNz4uXBciKhgq0YS4vSFuafNqfVTsLLNh6NOCS6C-pSx_ilYz7BDh1efPf_atWjxTk&usqp=CAU",
        src3: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/radisson-blu-plaza-1920-high.jpg",
        src4: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/cf/08/04/swimming-pool.jpg?w=600&h=-1&s=1",
        place: "Kerla",
        title:"Kerla Restaurent",
        description: "Enjoy the amazing sights of London with this stunning penthouse",
        price: 350,
        cutPrice: 450,
        sku: "123UIO",
        tags: "Rajsthan Jaipur",
        item_id : 28
    }

]

export default CardData;